version: '2'

networks:
  app-tier:
    driver: bridge
    
services:
  rabbitmq:
    image: 'rabbitmq:3'
    labels:
      kompose.service.type: nodeport
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    networks:
      - app-tier

  mongodb:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    networks:
      - app-tier
  
  microstreaminganalytics:
    image: jfernandez/micro-streaming-analytics:latest
    depends_on:
      - rabbitmq
      - mongodb
    links:
      - rabbitmq
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - app-tier

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local